### ISSUE TITLE
Add a __version__ global

### ISSUE THREAD

**Issue by rickheil** [AaronBurchfield/CloudFront-Middleware#1]
I'm in the midst of adding support to munkireport-php for reporting what version of middleware is installed on a client (see https://github.com/munkireport/munkireport-php/pull/737). To do so, it simply reads `__version__` from the middleware module. Can this be added? I'm happy to make the PR if you let me know what version number you'd like to start at. Thanks!

**Comment by AaronBurchfield** [comment]
Sounds good, I'll get version added. Looking forward to the new MunkiReport module!
