### ISSUE TITLE
10.14 FYI

### ISSUE THREAD

**Issue by clburlison** [AaronBurchfield/CloudFront-Middleware#4]
Just an FYI for anyone that is using this in production, 10.14 currently breaks this. You'll have to link against a custom version of OpenSSL, use a custom version of python (with a working copy of OpenSSL), install external python modules (boto3 should work + a rewrite), rewrite middleware script to not call out to OpenSSL, or some other option.

I'm still debating on what method I will use going forward.

**Comment by AaronBurchfield** [comment]
Hey @clburlison, thanks for opening this! 

What versions of 10.14 are you seeing this issue on? OpenSSL was broken from beta 1 to beta 2, but seems to be functional again as of beta 3. I've used [this](https://gist.github.com/AaronBurchfield/f0b63733fae70982440e5ee6ae6c4e7a) to successfully test CF middleware on beta 3, both 18A326g and 18A326h builds. 

I'm hoping I don't have to make any big changes until we're closer to a 10.14 GM.

**Comment by clburlison** [comment]
Aaron that’s awesome. I know I tested beta1. I’m glad they fixed it in beta
3 and will validate your findings tomorrow. Glad I opened this issue now. 😅

**Comment by clburlison** [comment]
Yay, this was fixed by Apple! Thanks for the info.
