### ISSUE TITLE
macOS 10.15 Catalina Issue

### ISSUE THREAD

**Issue by tbridge** [AaronBurchfield/CloudFront-Middleware#7]
Hi Aaron,

We're running into a challenge using the CloudFront-Middleware with Catalina's beta 1, and while I don't expect a fix in the short term, I wanted to let you know of the results of a run of Managed Software Center:

```WARNING: Ignoring /usr/local/munki/middleware_cloudfront.py because of error importing module.```

And, attempting to invoke the python script directly:

```tom@FVFT1CGVH3QD munki % ./middleware_cloudfront.py 
./middleware_cloudfront.py: line 1: Munki middleware provider to generate signed CloudFront requests.: command not found
./middleware_cloudfront.py: line 3: import: command not found
./middleware_cloudfront.py: line 4: import: command not found
./middleware_cloudfront.py: line 5: import: command not found
./middleware_cloudfront.py: line 6: import: command not found
from: can't read /var/mail/string
from: can't read /var/mail/OpenSSL.crypto
from: can't read /var/mail/OpenSSL.crypto
from: can't read /var/mail/OpenSSL.crypto
from: can't read /var/mail/Foundation
./middleware_cloudfront.py: line 13: __version__: command not found
Could not find command "=".
./middleware_cloudfront.py: line 16: KEYFILENAME: command not found
./middleware_cloudfront.py: line 17: syntax error near unexpected token `('
./middleware_cloudfront.py: line 17: `KEYFILEPATH = os.path.abspath(os.path.join(os.path.dirname(__file__),'```

**Comment by AaronBurchfield** [comment]
Hey Tom, thanks for opening this! 

As a temporary solution I was able to get this middleware working again on 10.15 by installing a few missing python modules. If Apple doesn't fix this in future versions of 10.15 we'll find a better way to bundle these modules.

```
sudo python -m ensurepip
sudo pip install asn1crypto enum34 py2-ipaddress
```

**Comment by tbridge** [comment]
Thanks so much for letting me know how to address this in the meantime!

Let me know if there's a radar I should dupe?

**Comment by erikng** [comment]
I wouldn't rely on apple's python moving forward. I would say that perhaps using relocatable python by Greg Neagle and quite possibly asking him to embed these modules within munki's upcoming embedded python so you can just link to it.

Thanks,
Erik Gomez
________________________________

**Comment by AaronBurchfield** [comment]
@tbridge I used the dev beta's feedback utility to open issue 6139616.

@erikng That's the plan since middleware is imported under munki's python runtime anyway. 👍

Holding this issue open until we have a long-term solution for 10.15.

**Comment by LcTrKiD** [comment]
https://github.com/AaronBurchfield/CloudFront-Middleware/pull/8 should fix this issue

**Comment by AaronBurchfield** [comment]
The [`v2-python3`](https://github.com/AaronBurchfield/CloudFront-Middleware/tree/v2-python3) branch adds python 3 support but does require changes to munki's python 3 framework. Instructions have been added to the README for building munkitools with the extra python module. 

Version 2 should also remain compatible with munki 3.6 and earlier with apple's python 2. 

I'd be interested in feedback and testing from anyone that has the time 👍Otherwise I'll merge this in a few days.

**Comment by LcTrKiD** [comment]
I'm testing the middleware with the changes I did here https://github.com/AaronBurchfield/CloudFront-Middleware/pull/9 with a few users.
So far so good

**Comment by AaronBurchfield** [comment]
These python3 changes have been merged, thanks again @LcTrKiD!
